# Here are all the worlds
kitpvpworld:
  - "kitpvp"
hub: 
  - "world"
skyblock1:
  - "skyblock_spawn"
skyblock2:
  - "island_normal_world"
tntrun: 
  - "tntrun"
builds: 
   - "builds"
event: 
   - "event"

# DO NOT TOUCH
name:
  - "%eazynick_display_name%"
parkour.location:
  x: "0"
  y: "0"
  z: "0"
hub.location:
  x: "0"
  y: "0"
  z: "0"

# Here is the MOTD
motd:
  - "         \u00A76\u00A7lFlash's Server \u00A7c◀ 1.8 - 1.16 ▶\u00A7r\n                  \u00A7a\u00A7lKitPvP ◊ SkyBlock"

