#worlds
kitpvpworld:
  - "kitpvp"
hub: 
  - "world"
skyblock:
  - "skyblock_spawn"
  - "island_normal_world"
tntrun: 
  - "tntrun"
builds: 
   - "builds"
event: 
   - "event"
name:
  - "%eazynick_display_name%"

#motd
motd:
  - "         \u00A76\u00A7lFlash's Server \u00A7c◀ 1.8 - 1.16 ▶\u00A7r\n                  \u00A7a\u00A7lKitPvP ◊ SkyBlock"

