name: Flash
version: @version@
main: me.flash.flash.Flash
#depend:
#  - Vault
commands:
  loopkill:
    description: Loop Kill a player
  tpall:
    description: Teleport all players in your server to you
  teleport:
    description: Teleport players
    aliases:
      - tp
      - tpto
      - teleportto
  silentteleport:
    description: Silently teleport players
    aliases:
      - silenttp
      - silenttpto
      - silentteleportto
  kill:
    description: Kill a player
    aliases:
      - slay
  suggest:
    description: Suggest better things for the best minecraft server that exists.
  suggestions:
    description: Read suggestions
  sudo:
    description: Make another player say something
  silenttphere:
      description: ~BB
      aliases:
        - stph
        - silenttph
        - stphere
        - ss
  tphere:
    description: teleports the player to you
    aliases:
      - tph
      - s
  staffchat:
    description: Toggle staffchat
    aliases: sc
  walkspeed:
    description: Set your walk speed 1 - 10
    aliases: ws
  flyspeed:
    description: Set your flight speed 1 - 10
    aliases: fs
  gmsp:
    description: Change your gamemode to spectator mode
    aliases:
      - gmspectator
      - gm3
  gmc:
    description: Change your gamemode to creative mode
    aliases:
      - gmcreative
      - gm1
  gms:
    description: Change your gamemode to survival mode
    aliases:
      - gm0
      - gmsurvival
  gma:
    description: Change your gamemode to adventure mode
    aliases:
      - gm2
      - gmadventure
  kits:
    description: Show kits
  kit:
    description: Get a kit
  menu:
    description: open the server selector
  server:
    description: do /server to tp to a server.
  tab:
    description: tab
  vanish:
    description: vanish
    aliases:
      - v
  help:
    description: help
  stats:
    description: test
  msg:
    description: send a message
    aliases:
      - message
      - send
      - tell
      - m
  reply:
    description: reply to someone
    aliases:
      - r
      - respond
  speed:
    description: change speed
  wake:
    description: Wake up someone who fell asleep
  sethub:
    description: Set a hub
  players:
    description: gets all online players
  rank:
    description: test
  parkour:
    description: parkour