name: Flash
version: @version@
main: me.flash.flash.Flash
depend:
  - Vault
commands:
  feed:
    description: Feed a player
  hub:
    description: Go back to hub
    aliases:
      - lobby
      - l
  loopkill:
    description: Loop Kill a player
  broadcast:
    description: Broadcast
    aliases: bc
  clear:
    description: Clear
    aliases:
      - ci
      - clearinventory
      - cl
  check:
    descrpition: Check
  craft:
    description: Craft
  bcf:
    description: F
    aliases:
      - broadcastf
      - sudof
  discord:
    description: See the discord
  tpall:
    description: Teleport all players in your server to you
  clearall:
    description: Clear the inventory of everyone in your world.
    aliases:
      - ciall
      - clearinventoryall
  teleport:
    description: Teleport players
    aliases:
      - tp
      - tpto
      - teleportto
  silentteleport:
    description: Silently teleport players
    aliases:
      - silenttp
      - silenttpto
      - silentteleportto
  kill:
    description: Kill a player
    aliases:
      - slay
  colorlist:
    description: See all the colors of the rainbow
    aliases:
      - cll
  suggest:
    description: Suggest better things for the best minecraft server that exists.
  suggestions:
    description: Read suggestions
  back:
    description: Go back
  sudo:
    description: Make another player say something
  fly:
    description: fly
  silenttphere:
      description: ~BB
      aliases:
        - stph
        - silenttph
        - stphere
        - ss
  tphere:
    description: teleports the player to you
    aliases:
      - tph
      - s
  staffchat:
    description: Toggle staffchat
    aliases: sc
  flyspeed:
    description: Set your flight speed 1 - 10
    aliases: fs
  walkspeed:
    description: Set your flight speed 1 - 10
    aliases: ws
  gamemode:
    description: Set your gamemode
    aliases:
      - gmode
      - gm
  gmsp:
    description: Change your gamemode to spectator mode
    aliases:
      - gmspectator
      - gm3
  gmc:
    description: Change your gamemode to creative mode
    aliases:
      - gmcreative
      - gm1
  gms:
    description: Change your gamemode to survival mode
    aliases:
      - gm0
      - gmsurvival
  gma:
    description: Change your gamemode to adventure mode
    aliases:
      - gm2
      - gmadventure
  give:
    description: Give items to players.
  kits:
    description: Show kits
  kit:
    description: Get a kit
  menu:
    description: open the server selector
  server:
    description: do /server to tp to a server.
  tab:
    description: tab
  vanish:
    description: vanish
    aliases:
      - v
  enderchest:
    description: enderchest
    aliases:
      - ec
  help:
    description: help
  stats:
    description: test
  msg:
    description: send a message
    aliases:
      - message
      - send
      - tell
      - m
  reply:
    description: reply to someone
    aliases:
      - r
      - respond
  speed:
    description: change speed
  build:
    description: turn build on or off
    aliases:
      - break
  wake:
    description: Wake up someone who fell asleep
  sethub:
    description: Set a hub
  invsee:
    description: Opens a players inventory
    aliases:
      - openinv
      - inventory
      - inv
  players:
    description: gets all online players