name: Flash
version: @version@
main: me.flash.flash.Flash
commands:
  kfeed:
    description: feed an ugly player
  pro:
    description: you pwo
  kkick:
    description: Kick ugly players
  inventory:
    description: Sapling :D
  khub:
    description: Go to hub, kotin edition
  kloopkill:
    description: Loop Kill a noob such as S0EE
  kbroadcast:
    description: Broadcast, Kotlin edition
  kclear:
    description: Clear, Kotlin edition
  kclearchat:
    description: Clear the chat, Kotlin edition
  kcheck:
    descrpition: Check, Kotlin edition
  kcraft:
    description: Craft, Kotlin edition
  kf:
    description: F, Kotlin edition
  kdiscord:
    description: See the discord, Kotlin edition
  ktpall:
    description: TpAll, Kotlin edition
  kclearall:
    description: Clear the inventory of veryone in your world, Kotlin edition.
  kteleport:
    description: Teleport players, Kotlin edition
    aliases: ktp
  ksilentteleport:
    description: Silently teleport players, Kotlin edition
    aliases: kstp, ksilenttp
  kenderchest:
    description: Open an enderchest, Kotlin edition
    aliases: kec, kenderchest
  kkill:
    description: Kill a player, Kotlin edition
  kcolorlist:
    description: See all the colors of the rainbow, Kotlin edition
