name: Flash
version: @version@
main: me.flash.flash.Flash
commands:
  feed:
    description: feed an ugly player
  pro:
    description: you pwo
  kkick:
    description: Kick ugly players
  khub:
    description: Go to hub
  kloopkill:
    description: Loop Kill a noob such as S0EE
  kbroadcast:
    description: Broadcast
    aliases: kbc
  kclear:
    description: Clear
  kclearchat:
    description: Clear the chat
  kcheck:
    descrpition: Check
  kcraft:
    description: Craft
  kf:
    description: F
  kdiscord:
    description: See the discord
  ktpall:
    description: TpAll
  kclearall:
    description: Clear the inventory of everyone in your world.
  kteleport:
    description: Teleport players
    aliases: ktp
  ksilentteleport:
    description: Silently teleport players
    aliases: kstp, ksilenttp
  kenderchest:
    description: Open an enderchest
    aliases: kec, kenderchest
  kkill:
    description: Kill a player
  kcolorlist:
    description: See all the colors of the rainbow
  suggest:
    description: Suggest better things for the best minecraft server that exists.
  suggestions:
    description: Read suggestions
  kback:
    description: Go back
  kmutechat:
    description: Mute or unmute the chat globally.
  ksudo:
    description: Make another player say something